export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const GET_DIMENSION = "GET_DIMENSION";
export const SET_DIEMNSION = "SET_DIEMNSION";
